new workflow

diff --git a/.github/workflows/go-test.yml b/.github/workflows/go-test.yml
--- a/.github/workflows/go-test.yml
+++ b/.github/workflows/go-test.yml
@@ -1,27 +1,40 @@
 name: Go tests
 
-on: 
+on:
   push:
   pull_request:
 
 jobs:
   test:
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v4
+
       - uses: actions/setup-go@v5
         with:
           go-version: "1.25"
-      - run: go mod tidy
-      - run: go test -v -coverfile=coverage.out ./learning/1_fundamentals/... ./learning/2_Data_Modeling/...
-      - run: go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//' > coverage.txt
-      - name: Check Coverage threshold
+
+      - name: Download dependencies
+        run: go mod tidy
+
+      - name: Run tests with coverage
         run: |
-          COVERAGE=$(cat coverage.txt)
+          go test -v -coverprofile=coverage.out \
+            ./learning/1_fundamentals/... \
+            ./learning/2_Data_Modeling/...
+
+      - name: Check coverage threshold
+        run: |
+          COVERAGE=$(go tool cover -func=coverage.out | awk '/total:/ {gsub("%", "", $3); print $3}')
+
           echo "Test Coverage: ${COVERAGE}%"
-          if (( $(echo "$COVERAGE < 50" | bc -l) )); then 
-            echo "X Test coverage is ${COVERAGE}%, which is below  the reqiured 50% threshold"
-            exit 1
-          else
-            echo "Test coverage is ${COVERAGE}% which meets the 50% threshold"
-          fi
+
+          awk -v coverage="$COVERAGE" 'BEGIN {
+            if (coverage < 50) {
+              printf "X Test coverage is %.2f%%, which is below the required 50%% threshold\n", coverage
+              exit 1
+            } else {
+              printf "Test coverage is %.2f%%, which meets the 50%% threshold\n", coverage
+            }
+          }'
